In [1]:
import pandas as pd
from sympy import true

In [2]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [3]:
employee_df.describe()

              Salary  Years with Company
count      10.000000            10.00000
mean    22140.013000            10.10000
std     30613.044026             6.52261
min      2629.130000             2.00000
25%      5906.740000             5.50000
50%      9536.010000             9.50000
75%     17768.005000            12.75000
max    100000.000000            23.00000

**PRACTICE OPPORTUNITY #1 [OPTIONAL]:**
- **What's the name of the employee who was most loyal to the company?**
- **How can you filter out this employee features using Pandas? [external research is required]**

In [5]:
employee_df['Years with Company'] == 23

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: Years with Company, dtype: bool

In [6]:
employee_df[ employee_df['Years with Company'] == 23 ]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
4,Kate,Noor,5000.0,23,K8N 5H6,kate@hotmail.com

# CODING TASK #2. SELECTING COLUMNS FROM A DATAFRAME

In [7]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [8]:
sample = employee_df['Email']
sample

0             bird@gmail.com
1         nsmall@hotmail.com
2            azikez@gahew.mr
3           chanel@gmail.com
4           kate@hotmail.com
5            samer@gmail.com
6    heba.ismail@hotmail.com
7        Laila.a@hotmail.com
8             daafeja@boh.jm
9          guutodi@bigwoc.kw
Name: Email, dtype: str

In [9]:
type(sample)

pandas.Series

In [10]:
employee_df.Email

0             bird@gmail.com
1         nsmall@hotmail.com
2            azikez@gahew.mr
3           chanel@gmail.com
4           kate@hotmail.com
5            samer@gmail.com
6    heba.ismail@hotmail.com
7        Laila.a@hotmail.com
8             daafeja@boh.jm
9          guutodi@bigwoc.kw
Name: Email, dtype: str

In [11]:
employee_df['Years with Company']

0     3
1     8
2    17
3    12
4    23
5    13
6     7
7     5
8     2
9    11
Name: Years with Company, dtype: int64

In [13]:
sample = employee_df[['First Name', 'Salary']]
sample

  First Name     Salary
0       Mike    5000.00
1       Noah   10000.00
2       Nina    9072.02
3    Chanel    11072.02
4       Kate    5000.00
5      Samer  100000.00
6       Heba   50000.00
7      Laila   20000.00
8     Joseph    2629.13
9       Noah    8626.96

In [14]:
type(sample)

pandas.DataFrame

In [15]:
employee_df[1:4]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com

**PRACTICE OPPORTUNITY #2 [OPTIONAL]:**
- **Select the following columns from the dataFrame Salary, Years with Company, and Postal Code**

In [17]:
sample = employee_df[['Salary','Years with Company', 'Postal Code']]
sample

      Salary  Years with Company Postal Code
0    5000.00                   3     N94 3M0
1   10000.00                   8     N8S 14K
2    9072.02                  17     S1T 4E6
3   11072.02                  12     N7T 3E6
4    5000.00                  23     K8N 5H6
5  100000.00                  13     J7H 3HY
6   50000.00                   7     K8Y 3M8
7   20000.00                   5     J8Y 3M0
8    2629.13                   2     M6U 5U7
9    8626.96                  11     K2D 4M9

# CODING TASK #3. ADDING/DELETING COLUMNS TO DATAFRAME

In [18]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [19]:
employee_df['Age'] = [25, 26, 28, 30, 36, 22, 48, 55, 70, 65]

In [20]:
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Age
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com,25
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com,26
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr,28
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com,30
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com,36
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com,22
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com,48
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com,55
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm,70
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw,65

In [22]:
employee_df.insert(0, column='Credit Score', value=[680, 700, 750, 699, 550, 600, 750, 500, 520, 510])

In [23]:
employee_df

,Credit Score,Credir Score,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Age
0,680,680,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com,25
1,700,700,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com,26
2,750,750,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr,28
3,699,699,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com,30
4,550,550,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com,36
5,600,600,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com,22
6,750,750,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com,48
7,500,500,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com,55
8,520,520,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm,70
9,510,510,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw,65

In [24]:
del employee_df['Credit Score']
employee_df

,Credir Score,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Age
0,680,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com,25
1,700,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com,26
2,750,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr,28
3,699,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com,30
4,550,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com,36
5,600,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com,22
6,750,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com,48
7,500,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com,55
8,520,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm,70
9,510,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw,65

In [25]:
employee_df.drop(labels = ["Last Name", "Salary"], axis = 1, inplace = True)
employee_df

,Credir Score,First Name,Years with Company,Postal Code,Email,Age
0,680,Mike,3,N94 3M0,bird@gmail.com,25
1,700,Noah,8,N8S 14K,nsmall@hotmail.com,26
2,750,Nina,17,S1T 4E6,azikez@gahew.mr,28
3,699,Chanel,12,N7T 3E6,chanel@gmail.com,30
4,550,Kate,23,K8N 5H6,kate@hotmail.com,36
5,600,Samer,13,J7H 3HY,samer@gmail.com,22
6,750,Heba,7,K8Y 3M8,heba.ismail@hotmail.com,48
7,500,Laila,5,J8Y 3M0,Laila.a@hotmail.com,55
8,520,Joseph,2,M6U 5U7,daafeja@boh.jm,70
9,510,Noah,11,K2D 4M9,guutodi@bigwoc.kw,65

In [28]:
Years_with_company = employee_df.pop("Years with Company")
Years_with_company

0     3
1     8
2    17
3    12
4    23
5    13
6     7
7     5
8     2
9    11
Name: Years with Company, dtype: int64

**PRACTICE OPPORTUNITY #3 [OPTIONAL]:**
- **load the employee_information.csv file and perform the following: (assume any reasonable values)**
    - **Add a column indicating whether the employee has a mortgage or not**
    - **Add a column indicating the value of mortage in dollars**

In [36]:
employee_df.insert(2, column='Has Mortgage', value=[0, 1, 1, 0, 1, 0, 0, 1, 1, 0])
employee_df.insert(3, column='Mortgage value', value=[0, 200000, 98762, 0, 56789, 0, 0, 987654, 556788, 0])
employee_df

,Credir Score,First Name,Has Mortgage,Mortgage value,Postal Code,Email,Age
0,680,Mike,0,0,N94 3M0,bird@gmail.com,25
1,700,Noah,1,200000,N8S 14K,nsmall@hotmail.com,26
2,750,Nina,1,98762,S1T 4E6,azikez@gahew.mr,28
3,699,Chanel,0,0,N7T 3E6,chanel@gmail.com,30
4,550,Kate,1,56789,K8N 5H6,kate@hotmail.com,36
5,600,Samer,0,0,J7H 3HY,samer@gmail.com,22
6,750,Heba,0,0,K8Y 3M8,heba.ismail@hotmail.com,48
7,500,Laila,1,987654,J8Y 3M0,Laila.a@hotmail.com,55
8,520,Joseph,1,556788,M6U 5U7,daafeja@boh.jm,70
9,510,Noah,0,0,K2D 4M9,guutodi@bigwoc.kw,65

# CODING TASK #4. LABEL-BASED ELEMENTS SELECTION FROM A DATAFRAME ".LOC()"

In [37]:
employee_df = pd.read_csv('employee_information.csv', index_col='Last Name')
employee_df

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Moe,Mike,5000.00,3,N94 3M0,bird@gmail.com
Ryan,Noah,10000.00,8,N8S 14K,nsmall@hotmail.com
Keller,Nina,9072.02,17,S1T 4E6,azikez@gahew.mr
Steve,Chanel,11072.02,12,N7T 3E6,chanel@gmail.com
Noor,Kate,5000.00,23,K8N 5H6,kate@hotmail.com
Mo,Samer,100000.00,13,J7H 3HY,samer@gmail.com
Steve,Heba,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Aly,Laila,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Patton,Joseph,2629.13,2,M6U 5U7,daafeja@boh.jm
Moran,Noah,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [38]:
employee_df.sort_index(inplace=True)
employee_df

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Aly,Laila,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Keller,Nina,9072.02,17,S1T 4E6,azikez@gahew.mr
Mo,Samer,100000.00,13,J7H 3HY,samer@gmail.com
Moe,Mike,5000.00,3,N94 3M0,bird@gmail.com
Moran,Noah,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
Noor,Kate,5000.00,23,K8N 5H6,kate@hotmail.com
Patton,Joseph,2629.13,2,M6U 5U7,daafeja@boh.jm
Ryan,Noah,10000.00,8,N8S 14K,nsmall@hotmail.com
Steve,Chanel,11072.02,12,N7T 3E6,chanel@gmail.com
Steve,Heba,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com

In [41]:
employee_df.loc['Aly']

First Name                          Laila
Salary                            20000.0
Years with Company                      5
Postal Code                       J8Y 3M0
Email                 Laila.a@hotmail.com
Name: Aly, dtype: object

In [40]:
employee_df.loc[['Aly', 'Mo']]

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Aly,Laila,20000.0,5,J8Y 3M0,Laila.a@hotmail.com
Mo,Samer,100000.0,13,J7H 3HY,samer@gmail.com

In [42]:
employee_df.loc['Keller':'Noor']

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Keller,Nina,9072.02,17,S1T 4E6,azikez@gahew.mr
Mo,Samer,100000.00,13,J7H 3HY,samer@gmail.com
Moe,Mike,5000.00,3,N94 3M0,bird@gmail.com
Moran,Noah,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
Noor,Kate,5000.00,23,K8N 5H6,kate@hotmail.com

In [43]:
employee_df.loc[:'Mo']

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Aly,Laila,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Keller,Nina,9072.02,17,S1T 4E6,azikez@gahew.mr
Mo,Samer,100000.00,13,J7H 3HY,samer@gmail.com

In [51]:
employee_df.sample(n=5, axis=0)

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Moe,Mike,5000.00,3,N94 3M0,bird@gmail.com
Ryan,Noah,10000.00,8,N8S 14K,nsmall@hotmail.com
Steve,Chanel,11072.02,12,N7T 3E6,chanel@gmail.com
Noor,Kate,5000.00,23,K8N 5H6,kate@hotmail.com
Moran,Noah,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [52]:
employee_df.sample(frac=0.3, axis=0)

,First Name,Salary,Years with Company,Postal Code,Email
Last Name,,,,,
Steve,Heba,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Patton,Joseph,2629.13,2,M6U 5U7,daafeja@boh.jm
Mo,Samer,100000.00,13,J7H 3HY,samer@gmail.com

**PRACTICE OPPORTUNITY #4 [OPTIONAL]:**
- **Load the 'employee_information.csv' data and use the "first name" column as the index**
- **Randomly select 2 rows from the DataFrame. Rerun the code and ensure that random rows are being selected**

In [53]:
employee_df = pd.read_csv('employee_information.csv', index_col='First Name')
employee_df

,Last Name,Salary,Years with Company,Postal Code,Email
First Name,,,,,
Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [55]:
employee_df.sample(n=2, axis=0)

,Last Name,Salary,Years with Company,Postal Code,Email
First Name,,,,,
Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com

# CODING TASK #5. INTEGER INDEX-BASED ELEMENTS SELECTION FROM A DATAFRAME "iLOC()"

In [56]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [59]:
employee_df.iloc[[5, 6]]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
5,Samer,Mo,100000.0,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.0,7,K8Y 3M8,heba.ismail@hotmail.com

In [60]:
employee_df.iloc[9]

First Name                         Noah
Last Name                         Moran
Salary                          8626.96
Years with Company                   11
Postal Code                     K2D 4M9
Email                 guutodi@bigwoc.kw
Name: 9, dtype: object

In [61]:
employee_df.iloc[2:5]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com

In [62]:
employee_df.iloc[:4]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com

In [65]:
employee_df.iloc[4, 0:3]

First Name      Kate
Last Name       Noor
Salary        5000.0
Name: 4, dtype: object

In [66]:
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

**PRACTICE OPPORTUNITY #5: [OPTIONAL]**
- **Write a code that selects the last two rows in the DataFrame using two different methods**

In [67]:
employee_df.iloc[[8,9]]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [68]:
employee_df.iloc[8:9]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm

In [69]:
employee_df.iloc[8:]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [70]:
employee_df.iloc[-2:]

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

# CODING TASK #6. BROADCASTING OPERATIONS & SETTING NEW DATAFRAME VALUES

In [71]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [72]:
employee_df['Salary'] = employee_df['Salary'] + 1000

In [73]:
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,6000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,11000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,10072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,12072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,6000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,101000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,51000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,21000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,3629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,9626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [74]:
employee_df['Salary'] = employee_df['Salary'].add(1000)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,7000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,12000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,11072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,13072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,7000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,102000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,52000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,22000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,4629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,10626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [75]:
employee_df['Salary (CAD)'] = employee_df['Salary'].mul(1.3)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Salary (CAD)
0,Mike,Moe,7000.00,3,N94 3M0,bird@gmail.com,9100.000
1,Noah,Ryan,12000.00,8,N8S 14K,nsmall@hotmail.com,15600.000
2,Nina,Keller,11072.02,17,S1T 4E6,azikez@gahew.mr,14393.626
3,Chanel,Steve,13072.02,12,N7T 3E6,chanel@gmail.com,16993.626
4,Kate,Noor,7000.00,23,K8N 5H6,kate@hotmail.com,9100.000
5,Samer,Mo,102000.00,13,J7H 3HY,samer@gmail.com,132600.000
6,Heba,Steve,52000.00,7,K8Y 3M8,heba.ismail@hotmail.com,67600.000
7,Laila,Aly,22000.00,5,J8Y 3M0,Laila.a@hotmail.com,28600.000
8,Joseph,Patton,4629.13,2,M6U 5U7,daafeja@boh.jm,6017.869
9,Noah,Moran,10626.96,11,K2D 4M9,guutodi@bigwoc.kw,13815.048

In [76]:
employee_df[4, 5] = 'kate.noor@gmail.com'
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Salary (CAD),"(4, 5)"
0,Mike,Moe,7000.00,3,N94 3M0,bird@gmail.com,9100.000,kate.noor@gmail.com
1,Noah,Ryan,12000.00,8,N8S 14K,nsmall@hotmail.com,15600.000,kate.noor@gmail.com
2,Nina,Keller,11072.02,17,S1T 4E6,azikez@gahew.mr,14393.626,kate.noor@gmail.com
3,Chanel,Steve,13072.02,12,N7T 3E6,chanel@gmail.com,16993.626,kate.noor@gmail.com
4,Kate,Noor,7000.00,23,K8N 5H6,kate@hotmail.com,9100.000,kate.noor@gmail.com
5,Samer,Mo,102000.00,13,J7H 3HY,samer@gmail.com,132600.000,kate.noor@gmail.com
6,Heba,Steve,52000.00,7,K8Y 3M8,heba.ismail@hotmail.com,67600.000,kate.noor@gmail.com
7,Laila,Aly,22000.00,5,J8Y 3M0,Laila.a@hotmail.com,28600.000,kate.noor@gmail.com
8,Joseph,Patton,4629.13,2,M6U 5U7,daafeja@boh.jm,6017.869,kate.noor@gmail.com
9,Noah,Moran,10626.96,11,K2D 4M9,guutodi@bigwoc.kw,13815.048,kate.noor@gmail.com

**PRACTICE OPPORTUNITY #6 [OPTIONAL]:**
- **Let's assume that all employees have been performing really well and their salaries have increased by 12% annualy. Calculate the sum of all employees salaries.**

In [83]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [84]:
employee_df['Salary New'] = employee_df['Salary'] + (employee_df['Salary'].mul(0.12))

In [85]:
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email,Salary New
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com,5600.0000
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com,11200.0000
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr,10160.6624
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com,12400.6624
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com,5600.0000
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com,112000.0000
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com,56000.0000
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com,22400.0000
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm,2944.6256
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw,9662.1952

In [86]:
employee_df['Salary New'].sum()

np.float64(247968.1456)

In [88]:
print("Total Salary of all employees: ${}".format(employee_df['Salary New'].sum()))

Total Salary of all employees: $247968.1456

# CODING TASK #7. PERFORM PANDAS DATAFRAMES SORTING AND ORDERING

In [89]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [92]:
employee_df.sort_values(by='Years with Company')

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com

In [95]:
employee_df.sort_values(by='Years with Company', ascending=False)

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm

In [96]:
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [97]:
employee_df.sort_values(by='Years with Company', ascending=True, inplace=True)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com

In [98]:
employee_df.sort_values(by='Years with Company', ascending=False, inplace=True)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm

In [99]:
employee_df.sort_index(inplace=True)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

**PRACTICE OPPORTUNITY #7 [OPTIONAL]:**
- **Sort employees by salaries instead of years with Company. Make sure to update values in-memory.**

In [101]:
employee_df.sort_values(by='Salary', ascending=True, inplace=True)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com