CODING TASK #1. PANDAS DATAFRAME 101

In [3]:
import pandas as pd

In [4]:
employee_df = pd.DataFrame({
    'Employee ID': [1, 2, 3, 4],
    'Employee Name': ['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Annual Salary [$]': [35000, 40000, 100000, 25000],
    'Years with Company': [5, 7, 10, 1]
})

employee_df

   Employee ID   Employee Name  Annual Salary [$]  Years with Company
0            1       Laila Aly              35000                   5
1            2      Kate Steve              40000                   7
2            3    Nicole Mitch             100000                  10
3            4  Francis Morris              25000                   1

In [5]:
type(employee_df)

pandas.DataFrame

In [6]:
employee_df.head(3)

   Employee ID Employee Name  Annual Salary [$]  Years with Company
0            1     Laila Aly              35000                   5
1            2    Kate Steve              40000                   7
2            3  Nicole Mitch             100000                  10

In [7]:
employee_df.tail(1)

   Employee ID   Employee Name  Annual Salary [$]  Years with Company
3            4  Francis Morris              25000                   1

CODING TASK #2. READ CSV DATA USING PANDAS AND PERFORM STATISTICAL DATA ANALYSIS

In [9]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [10]:
employee_df.describe()

              Salary  Years with Company
count      10.000000            10.00000
mean    22140.013000            10.10000
std     30613.044026             6.52261
min      2629.130000             2.00000
25%      5906.740000             5.50000
50%      9536.010000             9.50000
75%     17768.005000            12.75000
max    100000.000000            23.00000

CODING TASK #3. SETTING/RESETTING PANDAS DATAFRAME INDEX

In [11]:
employee_df = pd.read_csv('employee_information.csv')
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [12]:
employee_df.set_index("First Name", inplace=True)

In [13]:
employee_df

,Last Name,Salary,Years with Company,Postal Code,Email
First Name,,,,,
Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [14]:
employee_df.reset_index(inplace=True)
employee_df

,First Name,Last Name,Salary,Years with Company,Postal Code,Email
0,Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
1,Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
2,Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
3,Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
4,Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
5,Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
6,Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
7,Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
8,Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
9,Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

In [15]:
employee_df = pd.read_csv('employee_information.csv', index_col='First Name')
employee_df

,Last Name,Salary,Years with Company,Postal Code,Email
First Name,,,,,
Mike,Moe,5000.00,3,N94 3M0,bird@gmail.com
Noah,Ryan,10000.00,8,N8S 14K,nsmall@hotmail.com
Nina,Keller,9072.02,17,S1T 4E6,azikez@gahew.mr
Chanel,Steve,11072.02,12,N7T 3E6,chanel@gmail.com
Kate,Noor,5000.00,23,K8N 5H6,kate@hotmail.com
Samer,Mo,100000.00,13,J7H 3HY,samer@gmail.com
Heba,Steve,50000.00,7,K8Y 3M8,heba.ismail@hotmail.com
Laila,Aly,20000.00,5,J8Y 3M0,Laila.a@hotmail.com
Joseph,Patton,2629.13,2,M6U 5U7,daafeja@boh.jm
Noah,Moran,8626.96,11,K2D 4M9,guutodi@bigwoc.kw

FINAL CAPSTONE PROJECT

- **In this project, we will perform basic Exploratory Data Analysis (EDA) on the University Admissions Dataset**
- **Using the "university_admision.csv" included in the course package, write a python script to perform the following tasks:**
    - **1. Import the "university_admission.csv" file using Pandas**
    - **2. Display the first and last 8 rows in the DataFrame**
    - **3. Obtain the shape of the DataFrame**
    - **4. Calculate the average, min and max values for the LOR and SOP Columns**
    - **5. Use the GRE Score as the pandas dataframe index**
- **Columns definitions are as listed below:**
    - GRE Scores (out of 340)
    - TOEFL Scores (out of 120)
    - University Rating (out of 5)
    - Statement of Purpose (SOP)
    - Letter of Recommendation (LOR) Strength (out of 5)
    - Undergraduate GPA (out of 10)
    - Research Experience (either 0 or 1)
    - Chance of admission (ranging from 0 to 1)

In [23]:
university_adminssion = pd.read_csv('university_admission.csv')
university_adminssion.head(8)

,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admission
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65
5,330,115,5,4.5,3.0,9.34,1,0.90
6,321,109,3,3.0,4.0,8.20,1,0.75
7,308,101,2,3.0,4.0,7.90,0,0.68

In [24]:
university_adminssion.tail(8)

,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admission
992,298,101,4,2.5,4.5,7.69,1,0.53
993,300,95,2,3.0,1.5,8.22,1,0.62
994,301,99,3,2.5,2.0,8.45,1,0.68
995,332,108,5,4.5,4.0,9.02,1,0.87
996,337,117,5,5.0,5.0,9.87,1,0.96
997,330,120,5,4.5,5.0,9.56,1,0.93
998,312,103,4,4.0,5.0,8.43,0,0.73
999,327,113,4,4.5,4.5,9.04,0,0.84

In [19]:
university_adminssion.describe()

,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admission
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.00000
mean,316.472000,107.193000,3.114000,3.374000,3.484000,8.57644,0.560000,0.72174
std,11.289494,6.079368,1.142939,0.990507,0.924986,0.60451,0.496635,0.14107
min,290.000000,92.000000,1.000000,1.000000,1.000000,6.80000,0.000000,0.34000
25%,308.000000,103.000000,2.000000,2.500000,3.000000,8.12750,0.000000,0.63000
50%,317.000000,107.000000,3.000000,3.500000,3.500000,8.56000,1.000000,0.72000
75%,325.000000,112.000000,4.000000,4.000000,4.000000,9.04000,1.000000,0.82000
max,340.000000,120.000000,5.000000,5.000000,5.000000,9.92000,1.000000,0.97000

In [25]:
university_adminssion.columns

Index(['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance_of_Admission'],
      dtype='str')

In [26]:
university_adminssion.shape

(1000, 8)

In [27]:
university_adminssion.isnull().sum()

GRE_Score              0
TOEFL_Score            0
University_Rating      0
SOP                    0
LOR                    0
CGPA                   0
Research               0
Chance_of_Admission    0
dtype: int64

In [28]:
university_adminssion.describe()

,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admission
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.00000
mean,316.472000,107.193000,3.114000,3.374000,3.484000,8.57644,0.560000,0.72174
std,11.289494,6.079368,1.142939,0.990507,0.924986,0.60451,0.496635,0.14107
min,290.000000,92.000000,1.000000,1.000000,1.000000,6.80000,0.000000,0.34000
25%,308.000000,103.000000,2.000000,2.500000,3.000000,8.12750,0.000000,0.63000
50%,317.000000,107.000000,3.000000,3.500000,3.500000,8.56000,1.000000,0.72000
75%,325.000000,112.000000,4.000000,4.000000,4.000000,9.04000,1.000000,0.82000
max,340.000000,120.000000,5.000000,5.000000,5.000000,9.92000,1.000000,0.97000

In [29]:
university_adminssion = pd.read_csv('university_admission.csv', index_col='GRE_Score')
university_adminssion

,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admission
GRE_Score,,,,,,,
337,118,4,4.5,4.5,9.65,1,0.92
324,107,4,4.0,4.5,8.87,1,0.76
316,104,3,3.0,3.5,8.00,1,0.72
322,110,3,3.5,2.5,8.67,1,0.80
314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...
332,108,5,4.5,4.0,9.02,1,0.87
337,117,5,5.0,5.0,9.87,1,0.96
330,120,5,4.5,5.0,9.56,1,0.93
312,103,4,4.0,5.0,8.43,0,0.73
327,113,4,4.5,4.5,9.04,0,0.84